/**
 * The 39 icons, inlined.
 *
 * GENERATED by `scripts/generate-icons.mjs` from `docs/art-drops/`. Re-run that
 * script rather than editing this file; the drops are the source of truth and
 * this is a transcription of them.
 *
 *   nav set   7  sundry-icon-set-cplus
 *   drop A   22  sundry-icon-set-cplus-drop-a
 *   drop B   10  sundry-icon-set-cplus-drop-b
 *
 * Why the geometry is in a TypeScript module and not somewhere more obvious:
 *
 *  - **`<img src="…">` cannot work.** An `<img>` renders in its own document and
 *    inherits no `color`, so every `currentColor` in these files would resolve to
 *    black. The whole point of the drop is that one geometry serves both themes,
 *    and `<img>` is the trap in the obvious approach.
 *  - **A sprite plus `<use href>`** works, and the drops ship sprites, but it buys
 *    a request, a cache-busting story and a `public/` path that has to stay stable.
 *    All 39 are 19 KB before compression — less than one of the two font subsets
 *    already shipping — so there is nothing to win and machinery to lose.
 *  - **`vite-plugin-svgr`** is a build dependency in a repo that deliberately has
 *    neither a router nor a state library. One component is less than one plugin.
 *
 * Colour is not decided here. Every shape is `currentColor`, so an icon is
 * whatever colour its container's text is — which is why `theme.test.ts` can go
 * on being the only place that knows what the app's colours are.
 */

import { useId, type ReactElement } from 'react';

/**
 * Mints a document-unique id from the one the drop wrote. See the generator's
 * header: 22 of the 46 files carry a `<mask>`, and two instances of the same
 * icon on one page would otherwise repeat its id.
 */
type Mint = (id: string) => string;

/** A drawing is the children of the `<svg>`, not the `<svg>`. */
type Variant = (u: Mint) => ReactElement;

/** At or below this size the optical variant is used, for the seven that ship one. */
export const MICRO_MAX = 14;

export const ICON_NAMES = [
  'add',
  'alert',
  'budgets',
  'calendar',
  'calendar-week',
  'category',
  'check',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'close',
  'compose',
  'dark-mode',
  'delete',
  'edit',
  'expenses',
  'export',
  'external-link',
  'filter',
  'home',
  'import',
  'info',
  'light-mode',
  'merchant',
  'on-track',
  'receipt-scan',
  'receipt-view',
  'recurring',
  'retry',
  'search',
  'select-all',
  'settings',
  'sign-out',
  'sort-ascending',
  'sort-descending',
  'sort-none',
  'trend-down',
  'trend-up',
  'undo',
] as const;

export type IconName = (typeof ICON_NAMES)[number];

/** The seven with a hand-drawn 14px cut. The other thirty-two fall back to base. */
export const MICRO_ICON_NAMES: readonly IconName[] = [
  'external-link',
  'info',
  'sort-ascending',
  'sort-descending',
  'sort-none',
  'trend-down',
  'trend-up',
];

const BASE: Record<IconName, Variant> = {
  'add': u => (
    <>
      <defs>
        <mask id={u('addMask')}>
          <rect width="24" height="24" fill="white" />
          <rect x="10.9" y="7" width="2.2" height="10" rx="1.1" fill="black" />
          <rect x="7" y="10.9" width="10" height="2.2" rx="1.1" fill="black" />
        </mask>
      </defs>
      <rect x="3.5" y="3.5" width="17" height="17" rx="5" fill="currentColor" mask={`url(#${u('addMask')})`} />
    </>
  ),
  'alert': u => (
    <>
      <defs>
        <mask id={u('alertMask')}>
          <rect width="24" height="24" fill="white" />
          <rect x="10.9" y="8" width="2.2" height="5.8" rx="1.1" fill="black" />
          <circle cx="12" cy="16.7" r="1.1" fill="black" />
        </mask>
      </defs>
      <path fill="currentColor" mask={`url(#${u('alertMask')})`} d="M11.1 3.7a1.1 1.1 0 0 1 1.8 0l8.2 13.5A1.2 1.2 0 0 1 20.1 19H3.9a1.2 1.2 0 0 1-1-1.8l8.2-13.5Z" />
    </>
  ),
  'budgets': u => (
    <>
      <defs>
        <mask id={u('budgetMask')}>
          <rect width="24" height="24" fill="black" />
          <circle cx="12" cy="12" r="9" fill="white" />
          <path d="M12 12 V2.8" stroke="black" strokeWidth="1.7" strokeLinecap="round" />
          <path d="M12 12 L20.1 16.8" stroke="black" strokeWidth="1.7" strokeLinecap="round" />
          <path d="M12 12 L4.2 16.9" stroke="black" strokeWidth="1.7" strokeLinecap="round" />
        </mask>
      </defs>
      <circle cx="12" cy="12" r="9" fill="currentColor" mask={`url(#${u('budgetMask')})`} />
    </>
  ),
  'calendar': u => (
    <>
      <defs>
        <mask id={u('calMask')}>
          <rect width="24" height="24" fill="white" />
          <rect x="7" y="10.2" width="10" height="1.7" rx=".85" fill="black" />
          <rect x="7" y="14.1" width="3.2" height="2.7" rx=".6" fill="black" />
          <rect x="11.4" y="14.1" width="2.4" height="2.7" rx=".6" fill="black" />
        </mask>
      </defs>
      <rect x="4" y="5.2" width="16" height="15" rx="3" fill="currentColor" mask={`url(#${u('calMask')})`} />
      <rect x="7" y="2.6" width="2.2" height="5" rx="1.1" fill="currentColor" />
      <rect x="14.8" y="2.6" width="2.2" height="5" rx="1.1" fill="currentColor" />
    </>
  ),
  'calendar-week': u => (
    <>
      <defs>
        <mask id={u('calendarWeekMask')}>
          <rect width="24" height="24" fill="white" />
          <circle cx="6.2" cy="12.1" r=".8" fill="black" />
          <circle cx="8.15" cy="12.1" r=".8" fill="black" />
          <circle cx="10.1" cy="12.1" r=".8" fill="black" />
          <circle cx="12.05" cy="12.1" r=".8" fill="black" />
          <circle cx="14" cy="12.1" r=".8" fill="black" />
          <circle cx="15.95" cy="12.1" r=".8" fill="black" />
          <circle cx="17.9" cy="12.1" r=".8" fill="black" />
          <rect x="7.1" y="15.1" width="9.8" height="1.6" rx=".8" fill="black" />
        </mask>
      </defs>
      <rect x="3.7" y="5" width="16.6" height="15.1" rx="3.1" fill="currentColor" mask={`url(#${u('calendarWeekMask')})`} />
      <rect x="6.9" y="2.5" width="2.1" height="5" rx="1.05" fill="currentColor" />
      <rect x="15" y="2.5" width="2.1" height="5" rx="1.05" fill="currentColor" />
    </>
  ),
  'category': u => (
    <>
      <defs>
        <mask id={u('categoryMask')}>
          <rect width="24" height="24" fill="white" />
          <circle cx="15.85" cy="8.15" r="1.15" fill="black" />
        </mask>
      </defs>
      <path fill="currentColor" mask={`url(#${u('categoryMask')})`} d="M4.2 8.1 9.1 3.2h8.1q.65 0 1.1.45l2.05 2.05q.45.45.45 1.1v8.1L15.9 19.8a2.1 2.1 0 0 1-3 0L4.2 11.1a2.1 2.1 0 0 1 0-3Z" />
    </>
  ),
  'check': () => <path fill="currentColor" d="M9.8 17.6 4.9 12.7l1.9-1.9 3 3 7.5-7.5 1.9 1.9-9.4 9.4Z" />,
  'chevron-down': () => <path fill="currentColor" d="m5.4 9.1 6.6 6.6 6.6-6.6-2-2-4.6 4.6-4.6-4.6-2 2Z" />,
  'chevron-left': () => <path fill="currentColor" d="m14.9 5.4-6.6 6.6 6.6 6.6 2-2-4.6-4.6 4.6-4.6-2-2Z" />,
  'chevron-right': () => <path fill="currentColor" d="m9.1 5.4 6.6 6.6-6.6 6.6-2-2 4.6-4.6-4.6-4.6 2-2Z" />,
  'close': () => <path fill="currentColor" d="m6.2 4.6 5.8 5.8 5.8-5.8 1.6 1.6-5.8 5.8 5.8 5.8-1.6 1.6-5.8-5.8-5.8 5.8-1.6-1.6 5.8-5.8-5.8-5.8 1.6-1.6Z" />,
  'compose': u => (
    <>
      <defs>
        <mask id={u('composeMask')}>
          <rect width="24" height="24" fill="white" />
          <rect x="7.2" y="8.2" width="1.7" height="1.7" rx=".45" fill="black" />
          <rect x="10.3" y="8.2" width="1.7" height="1.7" rx=".45" fill="black" />
          <rect x="13.4" y="8.2" width="1.7" height="1.7" rx=".45" fill="black" />
          <rect x="16.5" y="8.2" width="1.7" height="1.7" rx=".45" fill="black" />
          <rect x="8.0" y="11.3" width="1.7" height="1.7" rx=".45" fill="black" />
          <rect x="11.1" y="11.3" width="1.7" height="1.7" rx=".45" fill="black" />
          <rect x="14.2" y="11.3" width="1.7" height="1.7" rx=".45" fill="black" />
          <rect x="8.1" y="15" width="7.8" height="1.7" rx=".8" fill="black" />
        </mask>
      </defs>
      <rect x="3.4" y="5.1" width="17.2" height="13.8" rx="3.2" fill="currentColor" mask={`url(#${u('composeMask')})`} />
    </>
  ),
  'dark-mode': u => (
    <>
      <defs>
        <mask id={u('moonMask')}>
          <rect width="24" height="24" fill="black" />
          <circle cx="11.25" cy="12" r="8.6" fill="white" />
          <circle cx="15.5" cy="8.4" r="7.5" fill="black" />
        </mask>
      </defs>
      <circle cx="11.25" cy="12" r="8.6" fill="currentColor" mask={`url(#${u('moonMask')})`} />
    </>
  ),
  'delete': u => (
    <>
      <defs>
        <mask id={u('trashMask')}>
          <rect width="24" height="24" fill="white" />
          <rect x="9.1" y="9.2" width="1.7" height="7.5" rx=".85" fill="black" />
          <rect x="13.2" y="9.2" width="1.7" height="7.5" rx=".85" fill="black" />
        </mask>
      </defs>
      <path fill="currentColor" mask={`url(#${u('trashMask')})`} d="M7 7h10l-.8 12.2A2 2 0 0 1 14.2 21H9.8a2 2 0 0 1-2-1.8L7 7Z" />
      <path fill="currentColor" d="M8.2 4.3h2.1l.6-1.3h2.2l.6 1.3h2.1A1.2 1.2 0 0 1 17 5.5V6H7v-.5a1.2 1.2 0 0 1 1.2-1.2Z" />
    </>
  ),
  'edit': () => (
    <>
      <path fill="currentColor" d="M4.2 16.8 4 20l3.2-.2L18.7 8.3 15.7 5.3 4.2 16.8Z" />
      <path fill="currentColor" d="M17 4a1.8 1.8 0 0 1 2.55 0l.45.45a1.8 1.8 0 0 1 0 2.55l-.35.35-3-3L17 4Z" />
    </>
  ),
  'expenses': () => <path fill="currentColor" fillRule="evenodd" d="M6.25 2.25 H17.75 Q19 2.25 19 3.5 V18.5 L17 21.5 L15 19.75 L13 21.5 L11 19.75 L9 21.5 L7 19.75 L5 21.5 V3.5 Q5 2.25 6.25 2.25 Z M8 7 H16 V8.8 H8 Z M8 11 H16 V12.8 H8 Z" />,
  'export': u => (
    <>
      <defs>
        <mask id={u('expMask')}>
          <rect width="24" height="24" fill="white" />
          <rect x="7" y="15.4" width="10" height="2.1" rx="1.05" fill="black" />
        </mask>
      </defs>
      <path fill="currentColor" mask={`url(#${u('expMask')})`} d="M4 14h4v3h8v-3h4v6H4v-6Z" />
      <path fill="currentColor" d="M10.6 13.5v-6H7.5L12 3l4.5 4.5h-3.1v6h-2.8Z" />
    </>
  ),
  'external-link': () => (
    <>
      <path fill="currentColor" d="M4.2 5.2h7v2.4H6.6v9.8h9.8v-4.6h2.4v7H4.2V5.2Z" />
      <path fill="currentColor" d="M13.2 4.2h6.6v6.6h-2.4V8.3l-6.1 6.1-1.7-1.7 6.1-6.1h-2.5V4.2Z" />
    </>
  ),
  'filter': () => <path fill="currentColor" d="M3.5 5h17L14 12.3v5.2l-4 2v-7.2L3.5 5Z" />,
  'home': () => <path fill="currentColor" fillRule="evenodd" d="M12 2.35 L21 9.85 V21 H14.7 V15.2 H9.3 V21 H3 V9.85 Z M10.35 21 V16.25 H13.65 V21 Z" />,
  'import': u => (
    <>
      <defs>
        <mask id={u('impMask')}>
          <rect width="24" height="24" fill="white" />
          <rect x="7" y="15.4" width="10" height="2.1" rx="1.05" fill="black" />
        </mask>
      </defs>
      <path fill="currentColor" mask={`url(#${u('impMask')})`} d="M4 14h4v3h8v-3h4v6H4v-6Z" />
      <path fill="currentColor" d="M10.6 4h2.8v6h3.1L12 14.5 7.5 10h3.1V4Z" />
    </>
  ),
  'info': u => (
    <>
      <defs>
        <mask id={u('infoMask')}>
          <rect width="24" height="24" fill="white" />
          <circle cx="12" cy="7.3" r="1.2" fill="black" />
          <rect x="10.9" y="10" width="2.2" height="6.7" rx="1.1" fill="black" />
        </mask>
      </defs>
      <circle cx="12" cy="12" r="9" fill="currentColor" mask={`url(#${u('infoMask')})`} />
    </>
  ),
  'light-mode': () => (
    <>
      <circle cx="12" cy="12" r="4.35" fill="currentColor" />
      <rect x="11.1" y="1.5" width="1.8" height="4" rx="0.9" fill="currentColor" transform="rotate(0 12 12)" />
      <rect x="11.1" y="1.5" width="1.8" height="4" rx="0.9" fill="currentColor" transform="rotate(45 12 12)" />
      <rect x="11.1" y="1.5" width="1.8" height="4" rx="0.9" fill="currentColor" transform="rotate(90 12 12)" />
      <rect x="11.1" y="1.5" width="1.8" height="4" rx="0.9" fill="currentColor" transform="rotate(135 12 12)" />
      <rect x="11.1" y="1.5" width="1.8" height="4" rx="0.9" fill="currentColor" transform="rotate(180 12 12)" />
      <rect x="11.1" y="1.5" width="1.8" height="4" rx="0.9" fill="currentColor" transform="rotate(225 12 12)" />
      <rect x="11.1" y="1.5" width="1.8" height="4" rx="0.9" fill="currentColor" transform="rotate(270 12 12)" />
      <rect x="11.1" y="1.5" width="1.8" height="4" rx="0.9" fill="currentColor" transform="rotate(315 12 12)" />
    </>
  ),
  'merchant': u => (
    <>
      <defs>
        <mask id={u('merchantMask')}>
          <rect width="24" height="24" fill="white" />
          <rect x="8" y="13" width="3.2" height="5.2" rx=".5" fill="black" />
          <rect x="13.2" y="13" width="3.1" height="3.1" rx=".5" fill="black" />
        </mask>
      </defs>
      <path fill="currentColor" mask={`url(#${u('merchantMask')})`} d="M5 9.2h14v10.3H5V9.2Z" />
      <path fill="currentColor" d="M4.1 4.3h15.8l1 4.2c-.6 1.6-1.7 2.4-3.2 2.4-1.2 0-2.1-.45-2.7-1.35-.65.9-1.65 1.35-3 1.35s-2.35-.45-3-1.35c-.6.9-1.5 1.35-2.7 1.35-1.5 0-2.6-.8-3.2-2.4l1-4.2Z" />
    </>
  ),
  'on-track': u => (
    <>
      <defs>
        <mask id={u('trackMask')}>
          <rect width="24" height="24" fill="white" />
          <path d="m8.1 12.2 2.5 2.5 5.2-5.2" fill="none" stroke="black" strokeWidth="2.1" strokeLinecap="round" strokeLinejoin="round" />
        </mask>
      </defs>
      <circle cx="12" cy="12" r="9" fill="currentColor" mask={`url(#${u('trackMask')})`} />
    </>
  ),
  'receipt-scan': u => (
    <>
      <defs>
        <mask id={u('receiptScanMask')}>
          <rect width="24" height="24" fill="white" />
          <rect x="9.2" y="9.2" width="5.6" height="1.55" rx=".75" fill="black" />
          <rect x="9.2" y="12.4" width="5.6" height="1.55" rx=".75" fill="black" />
        </mask>
      </defs>
      <path fill="currentColor" mask={`url(#${u('receiptScanMask')})`} d="M8.4 5.7h7.2q1 0 1 1v10.9 l-1.2 1.5-1.45-1.2-1.45 1.2-1.45-1.2-1.45 1.2-1.2-1.5V6.7q0-1 1-1Z" />
      <path fill="currentColor" d="M3.2 7.6V4.8q0-1.6 1.6-1.6h2.8v2H5.4q-.2 0-.2.2v2.2h-2Z M16.4 3.2h2.8q1.6 0 1.6 1.6v2.8h-2V5.4q0-.2-.2-.2h-2.2v-2Z M3.2 16.4h2v2.2q0 .2.2.2h2.2v2H4.8q-1.6 0-1.6-1.6v-2.8Z M18.8 16.4h2v2.8q0 1.6-1.6 1.6h-2.8v-2h2.2q.2 0 .2-.2v-2.2Z" />
    </>
  ),
  'receipt-view': u => (
    <>
      <defs>
        <mask id={u('receiptViewMask')}>
          <rect width="24" height="24" fill="white" />
          <path d="M8.2 12c1.4-2 2.7-3 3.8-3s2.4 1 3.8 3c-1.4 2-2.7 3-3.8 3s-2.4-1-3.8-3Z" fill="black" />
        </mask>
      </defs>
      <path fill="currentColor" mask={`url(#${u('receiptViewMask')})`} d="M6.2 3.3h11.6q1.1 0 1.1 1.1v13.1 l-1.45 2.1-1.8-1.45-1.8 1.45-1.8-1.45-1.8 1.45-1.8-1.45-1.45 2.1V4.4q0-1.1 1.1-1.1Z" />
      <circle cx="12" cy="12" r="1.15" fill="currentColor" />
    </>
  ),
  'recurring': () => (
    <>
      <path fill="currentColor" d="M5.1 8.1A8.4 8.4 0 0 1 18 6.2l1.9-1.9v5.9H14l2-2a5.7 5.7 0 0 0-8.9 1.4L5.1 8.1Z" />
      <path fill="currentColor" d="M18.9 15.9A8.4 8.4 0 0 1 6 17.8l-1.9 1.9v-5.9H10l-2 2a5.7 5.7 0 0 0 8.9-1.4l2 1.5Z" />
    </>
  ),
  'retry': u => (
    <>
      <defs>
        <mask id={u('retryMask')}>
          <rect width="24" height="24" fill="white" />
          <circle cx="12" cy="12" r="5.15" fill="black" />
          <path d="M15.8 3.6h5.3v5.6h-5.3Z" fill="black" />
        </mask>
      </defs>
      <circle cx="12" cy="12" r="8.8" fill="currentColor" mask={`url(#${u('retryMask')})`} />
      <path fill="currentColor" d="M15.7 3.6h5.4v5.4l-2.15-1.85A7.2 7.2 0 0 0 7.3 8.4L5.5 6.8a9.6 9.6 0 0 1 14.95-1.4L21.1 3.6h-5.4Z" />
    </>
  ),
  'search': u => (
    <>
      <defs>
        <mask id={u('searchMask')}>
          <rect width="24" height="24" fill="white" />
          <circle cx="10.5" cy="10.5" r="4.8" fill="black" />
        </mask>
      </defs>
      <circle cx="10.5" cy="10.5" r="8" fill="currentColor" mask={`url(#${u('searchMask')})`} />
      <path fill="currentColor" d="m15.8 14.2 5.1 5.1-1.6 1.6-5.1-5.1 1.6-1.6Z" />
    </>
  ),
  'select-all': u => (
    <>
      <defs>
        <mask id={u('selMask')}>
          <rect width="24" height="24" fill="white" />
          <path d="M9.4 12.6 11.3 14.5 15.7 10.1" fill="none" stroke="black" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
        </mask>
      </defs>
      <rect x="5.5" y="5.5" width="13" height="13" rx="3" fill="currentColor" mask={`url(#${u('selMask')})`} />
      <path fill="currentColor" d="M3.2 7.4V5a1.8 1.8 0 0 1 1.8-1.8h2.4v1.7H5a.1.1 0 0 0-.1.1v2.4H3.2Zm13.4-4.2H19A1.8 1.8 0 0 1 20.8 5v2.4h-1.7V5a.1.1 0 0 0-.1-.1h-2.4V3.2ZM3.2 16.6h1.7V19c0 .06.04.1.1.1h2.4v1.7H5A1.8 1.8 0 0 1 3.2 19v-2.4Zm15.9 0h1.7V19a1.8 1.8 0 0 1-1.8 1.8h-2.4v-1.7H19a.1.1 0 0 0 .1-.1v-2.4Z" />
    </>
  ),
  'settings': u => (
    <>
      <defs>
        <mask id={u('gearMask')}>
          <rect width="24" height="24" fill="white" />
          <circle cx="12" cy="12" r="3.25" fill="black" />
        </mask>
      </defs>
      <polygon points="12.000,2.700 13.814,2.879 14.794,5.256 16.056,5.930 18.576,5.424 19.733,6.833 18.744,9.206 19.160,10.576 21.300,12.000 21.121,13.814 18.744,14.794 18.070,16.056 18.576,18.576 17.167,19.733 14.794,18.744 13.424,19.160 12.000,21.300 10.186,21.121 9.206,18.744 7.944,18.070 5.424,18.576 4.267,17.167 5.256,14.794 4.840,13.424 2.700,12.000 2.879,10.186 5.256,9.206 5.930,7.944 5.424,5.424 6.833,4.267 9.206,5.256 10.576,4.840" fill="currentColor" mask={`url(#${u('gearMask')})`} />
    </>
  ),
  'sign-out': u => (
    <>
      <defs>
        <mask id={u('signOutMask')}>
          <rect width="24" height="24" fill="white" />
          <rect x="6.8" y="6.7" width="4.2" height="10.6" rx=".7" fill="black" />
        </mask>
      </defs>
      <path fill="currentColor" mask={`url(#${u('signOutMask')})`} d="M4.1 3.4h9.2q1.1 0 1.1 1.1v15q0 1.1-1.1 1.1H4.1V3.4Z" />
      <path fill="currentColor" d="M12.4 10.6h5.1l-1.8-1.8 1.6-1.6 4.5 4.8-4.5 4.8-1.6-1.6 1.8-1.8h-5.1v-2.8Z" />
    </>
  ),
  'sort-ascending': () => (
    <>
      <path fill="currentColor" d="M5 17h8v2H5v-2Zm0-5h7v2H5v-2Zm0-5h6v2H5V7Z" />
      <path fill="currentColor" d="M17 18V8.6l-2.2 2.2-1.5-1.5L18 4.6l4.7 4.7-1.5 1.5L19 8.6V18h-2Z" />
    </>
  ),
  'sort-descending': () => (
    <>
      <path fill="currentColor" d="M5 7h8v2H5V7Zm0 5h7v2H5v-2Zm0 5h6v2H5v-2Z" />
      <path fill="currentColor" d="M17 6v9.4l-2.2-2.2-1.5 1.5 4.7 4.7 4.7-4.7-1.5-1.5-2.2 2.2V6h-2Z" />
    </>
  ),
  'sort-none': () => <path fill="currentColor" d="M6.2 9.1 9 6.3l2.8 2.8-1.5 1.5L10 10.3V17H8v-6.7l-.3.3-1.5-1.5Zm6 5.8 1.5-1.5.3.3V7h2v6.7l.3-.3 1.5 1.5-2.8 2.8-2.8-2.8Z" />,
  'trend-down': () => <path fill="currentColor" d="m4.3 7.2 4.7 4.7 3.1-3.1 6.4 6.4h-3v2.2h6.8v-6.8h-2.2v3l-8-8L9 8.7 5.8 5.5 4.3 7.2Z" />,
  'trend-up': () => <path fill="currentColor" d="M4.3 16.8 9 12.1l3.1 3.1 6.4-6.4h-3V6.6h6.8v6.8h-2.2v-3l-8 8-3.1-3.1-3.2 3.2-1.5-1.7Z" />,
  'undo': () => <path fill="currentColor" d="M9.2 5.2 4.3 9.4l4.9 4.2v-2.5h4.1c3.1 0 5.2 1.5 6.5 4.6-.1-5.3-2.8-8.2-7.8-8.2H9.2V5.2Z" />,
};

const MICRO: Partial<Record<IconName, Variant>> = {
  'external-link': () => (
    <>
      <path fill="currentColor" d="M5 6h6v2H7v9h9v-4h2v6H5V6Z" />
      <path fill="currentColor" d="M13 4h7v7h-2.2V7.8l-6.2 6.2-1.6-1.6 6.2-6.2H13V4Z" />
    </>
  ),
  'info': u => (
    <>
      <defs>
        <mask id={u('infoMicroMask')}>
          <rect width="24" height="24" fill="white" />
          <circle cx="12" cy="7.4" r="1.35" fill="black" />
          <rect x="10.75" y="10" width="2.5" height="6.5" rx="1.25" fill="black" />
        </mask>
      </defs>
      <circle cx="12" cy="12" r="8.8" fill="currentColor" mask={`url(#${u('infoMicroMask')})`} />
    </>
  ),
  'sort-ascending': () => (
    <>
      <path fill="currentColor" d="M5 17h8v2H5v-2Zm0-5h7v2H5v-2Zm0-5h6v2H5V7Z" />
      <path fill="currentColor" d="M17 18V8.6l-2.2 2.2-1.5-1.5L18 4.6l4.7 4.7-1.5 1.5L19 8.6V18h-2Z" />
    </>
  ),
  'sort-descending': () => (
    <>
      <path fill="currentColor" d="M5 7h8v2H5V7Zm0 5h7v2H5v-2Zm0 5h6v2H5v-2Z" />
      <path fill="currentColor" d="M17 6v9.4l-2.2-2.2-1.5 1.5 4.7 4.7 4.7-4.7-1.5-1.5-2.2 2.2V6h-2Z" />
    </>
  ),
  'sort-none': () => <path fill="currentColor" d="M6.2 9.1 9 6.3l2.8 2.8-1.5 1.5L10 10.3V17H8v-6.7l-.3.3-1.5-1.5Zm6 5.8 1.5-1.5.3.3V7h2v6.7l.3-.3 1.5 1.5-2.8 2.8-2.8-2.8Z" />,
  'trend-down': () => <path fill="currentColor" d="m4.3 7.2 4.7 4.7 3.1-3.1 6.4 6.4h-3v2.2h6.8v-6.8h-2.2v3l-8-8L9 8.7 5.8 5.5 4.3 7.2Z" />,
  'trend-up': () => <path fill="currentColor" d="M4.3 16.8 9 12.1l3.1 3.1 6.4-6.4h-3V6.6h6.8v6.8h-2.2v-3l-8 8-3.1-3.1-3.2 3.2-1.5-1.7Z" />,
};

export type IconProps = {
  name: IconName;
  /** Rendered box in CSS pixels. 14 or below picks the micro cut where one exists. */
  size?: number;
  className?: string;
};

/**
 * Always `aria-hidden`. Two cases and they are not the same: an icon beside its
 * own label is decorative and the label carries the meaning; an icon alone in a
 * control means the *button* needs an `aria-label`. Neither case wants a name on
 * the `<svg>`, and a component that offered one would invite the third, wrong
 * answer — a picture that announces itself twice.
 */
export function Icon({ name, size = 20, className }: IconProps): ReactElement {
  const instance = useId().replace(/[^a-zA-Z0-9]/g, '');

  const micro: Variant | undefined = size <= MICRO_MAX ? MICRO[name] : undefined;
  const base: Variant | undefined = BASE[name];
  const draw = micro ?? base;

  // Loudly, not as an empty box: a typo in a name is invisible otherwise, and
  // `IconName` only guards the call sites the compiler can see.
  if (!draw) throw new Error(`Icon: unknown name "${String(name)}"`);

  return (
    <svg
      className={className ? `icon ${className}` : 'icon'}
      data-icon={name}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
    >
      {draw(id => `${id}-${instance}`)}
    </svg>
  );
}
